[package]
name = "server"
edition.workspace = true
version.workspace = true

[dependencies]
rusqlite={version="0.31", features=["uuid"]}
common.workspace = true
rocket="0.5"
serde.workspace = true
uuid.workspace = true